crm_input_app/urls.py
"""Defines URL patterns for crm_input_app """
from django.conf.urls import url
from . import views

urlpatterns=[
    #Home page
    url(r'^$', views.index, name='index'),
    
    #show all parameter sets
    url(r'^parasList/$',views.parasList,name='parasList'),

    #show each parameter set details

    url(r'^parasDetail/(?P<paras_id>\d+)$',views.parasDetail,name='parasDetail'),
 
    #add new parameter sets
    url(r'^new_paras/$', views.new_paras, name='new_paras'),


    # view results page

    url(r'^result/(?P<paras_id>\d+)$', views.getResult, name='result'),

    # edit parameters page
    url(r'^edit_paras/(?P<paras_id>\d+)$', views.edit_paras, name='edit_paras'),

]

crm_proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'', include('crm_input_app.urls', namespace='crm_input_app')),

    url(r'^users/', include('users.urls', namespace='users')),
    
]

users/urls.py
""" Defines URL patterns for users"""

from django.conf.urls import url
from django.contrib.auth.views import login


from . import views

urlpatterns=[
    # Login page
    url(r'^login/$', login, {'template_name':'users/login.html'},
    name='login'),
    
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register,name='register'),

]

crm_input_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ParaSet(models.Model):
    """A set of parameters that users enters"""
    
    YES_NO_CHS = (
        ('1', 'Yes'),
        ('0', 'No'),
    )    
    
    ASSET_LOC_CHS = (
        ('1', 'National Data Center'),
        ('2', 'Regional'),
        ('3','Server Room'),
        ('4','Exposed'),
        ('5', 'Vendor Hosted'),
    )    
    
    SOLU_PROV_CHS=(
    ('1','Reputable Vendor'),
    ('2','Not Reputable Vendor'),
    ('3','Mature Internal Team (Certified)'),
    )
    
    
    AUTHEN_CHS=(
    ('1','Anonymous (n/a)'),
    ('2','Local'),
    ('3','Central'),    
    )
    
    KNOWN_VUL_CHS=(
    ('1', 'Unknown'),
    ('2','Yes but no published exploit'),
    ('3', 'Yes but vulnerability and exploit not automated'),
    ('4', 'Yes and automated vulnerability but not automated exploit'),
    ('5',  "Yes and both vulnerability and exploit are automated")  ,  

    )
  
    
    control_fail_id=models.CharField("Control Failure ID", max_length=15)
    asset_id=models.CharField("Asset ID", max_length=15)
    control_name=models.CharField("Control Name", max_length=100)
    ctr_fail_desc=models.CharField("Control Failure Description", max_length=600)
    
    sensitive_data= models.CharField("Sensitive Data", choices=YES_NO_CHS, max_length=1)
    asset_loc=models.CharField("Asset Location", choices=ASSET_LOC_CHS, max_length=1 )    
    solution_prov=models.CharField("Solution Provider",choices=SOLU_PROV_CHS, max_length=1)
    pocs= models.CharField("Point of Care System", choices=YES_NO_CHS,max_length=1)
    auth_meth=models.CharField("Authentication Method", choices=AUTHEN_CHS, max_length=1)    
    cri_met=models.CharField("All criteria  well maintained are met", choices=YES_NO_CHS,max_length=1)
    wide_vul=models.CharField("Widely known vulnerability", choices=YES_NO_CHS,max_length=1)
    comp_ctr=models.CharField(" There is a compensating control", choices=YES_NO_CHS,max_length=1)
    internet_exp=models.CharField("Internet Exposed or in DMZ", choices=YES_NO_CHS,max_length=1)
    owner=models.ForeignKey(User)
   
    
    def __str__(self):
        """Return a string representation of the model"""
        return self.control_name

    def __iter__(self):
            
        for field in self._meta.get_fields():
           if field.name != "owner":


                value = getattr(self, field.name, None)

                if field.choices:
                    display=dict(field.choices)[value]
            
                else:
                    display=value

       
                yield ( field.verbose_name.title(), value, display)
        

crm_input_app/forms.py
from django import forms
from .models import ParaSet

class ParaSetForm(forms.ModelForm):
    class Meta:
        model=ParaSet
        
        fields=['control_fail_id','asset_id','control_name',
        'ctr_fail_desc','sensitive_data','asset_loc','solution_prov','pocs','auth_meth',
        'cri_met','wide_vul','comp_ctr','internet_exp']

crm_input_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from .models import ParaSet
from .forms import ParaSetForm


# Create your views here.
def index(request):
    """The home page for crm_input_app"""
    return render (request, 'crm_input_app/index.html')

@login_required
def parasList(request):
    """Show all parameters sets"""
    paraslist=ParaSet.objects.filter(owner=request.user).order_by('id')
    context={'paraslist':paraslist}
    return render(request, 'crm_input_app/parasList.html',context)

@login_required
def parasDetail(request, paras_id):
    """show parameter set details"""
    paras=ParaSet.objects.get(id=paras_id)
    #make sure the parameter set belongs to the current user.

    if paras.owner!= request.user:
        raise Http404
    context={'paras':paras}
    return render (request, 'crm_input_app/parasDetail.html',context)

@login_required
def new_paras(request):
    """Add new parameter set"""
    if request.method!='POST':
        #No data submitted;create a a blank form
        form=ParaSetForm()
    else:
        #POST data submitted; process data
        form=ParaSetForm(request.POST)
        if form.is_valid():
            new_data=form.save(commit=False)
            new_data.owner=request.user
            new_data.save()
            return HttpResponseRedirect(reverse ('crm_input_app:parasDetail',args=[new_data.id]))

    
    context= {'form':form}
    return render(request, 'crm_input_app/new_paras.html', context)    

@login_required
def getResult(request, paras_id):
    """show parameter set details"""
    paras=ParaSet.objects.get(id=paras_id)
    #make sure the parameter set belongs to the current user.

    if paras.owner!= request.user:
        raise Http404

    context={'paras':paras}
    return render (request, 'crm_input_app/result.html',context)

@login_required
def edit_paras(request, paras_id):
    """Edit an existing parameterset"""

    paras=ParaSet.objects.get(id=paras_id)

    #make sure the parameter set belongs to the current user.

    if paras.owner!= request.user:
        raise Http404

    if request.method!='POST':
        #initial request; pre-fill form with the current parameter set.
        form = ParaSetForm(instance=paras)
    else:
        #Post data submitted
        form=ParaSetForm(instance = paras, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse ('crm_input_app:parasDetail',args=[paras.id]))

    context={'paras':paras,'form':form}
    return render(request,'crm_input_app/edit_paras.html', context)

crm_input_app/templates/crm_input_app/base.html
{%load bootstrap3 %}

<!DOCTYPE html>

<html lang="en">

<head>
<meta charset ="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE-edge">
<meta name="viewport" content="width=device-width, inital-scale=1">

<title>Control Risk Model</title>

{% bootstrap_css %}
{% bootstrap_javascript %}
</head>

<body>
<!--- Static navbar-->

<nav class="navbar navbar-default navbar-static-top">

	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed"

			data-toggle="collapse" data-darget="#navbar"
			airia-expaned="false" aria-controls ="navbar">
			</button>

			<a class="navbar-brand" href="{% url 'crm_input_app:index'%}">Control Risk Model Home</a>
		</div>

		<div id="navbar" class="navbar-collapse collapse">
			{%if user.is_authenticated%}

			<ul class="nav navbar-nav">

				<li>  <a href="{% url 'crm_input_app:parasList'%}">Saved Parameter Set List</a>  </li>
				<li> <a href="{% url 'crm_input_app:new_paras'%}">Add a New Parameter Set</a> </li>
			</ul>

			{% endif%}


			<ul class="nav navbar-nav navbar-right">

			{%if user.is_authenticated%}
			<li> <a> Hello, {{user.username}}. </a> </li>
			<li> <a href="{% url 'users:logout'%}">log out</a></li>

			{%else%}

			<li> <a href="{%url 'users:register'%}">register</a> </li>
			<li> <a href="{%url 'users:login'%}">log in</a></li>

			{% endif%}

			</ul>
		</div> <!-- /.av-collapese-->
	</div>
</nav>

<div class="container">

	<div class= "page-header">
		{%block header%}
		{%endblock header%}
	</div>
	
	<div>
		{%block content%}
		{%endblock content%}
	</div

</div> <!--/container-->
</body>

crm_input_app/templates/crm_input_app/edit_paras.html
{%extends "crm_input_app/base.html"%}

{% load bootstrap3 %}



{% block header %}

	<h2> Edit this parameter set:</h2>

{% endblock header %}

{%block content%}
<p>Edit parameter set: {{paras}}</p>

<form action="{%url 'crm_input_app:edit_paras' paras.id%}" method='post'>
{%csrf_token%}

{%bootstrap_form form%}

<button name="Submit"> Save changes</button>
</form>



{% endblock content%}

crm_input_app/templates/crm_input_app/index.html
{%extends "crm_input_app/base.html"%}

{% block header %}

<div class ='jumbotron'>
	<h1> KP Control Risk Model </h1>
</div>

{% endblock header %}

{% block content %}


<p>Welcome to KP Control Risk Model Web Application!</p>

{%endblock content%}

crm_input_app/templates/crm_input_app/new_paras.html
{% extends "crm_input_app/base.html" %}

{% load bootstrap3 %}

{% block header %}

	<h2> Add a new parameter set:</h2>

{% endblock header %}

{%block content%}


	<form action="{%url 'crm_input_app:new_paras'%}" method='post' class="form">
		{%csrf_token%}

		{% bootstrap_form form %}

		

			<button name="Submit"> Add Parameter Set </button>

		

	</form>

{% endblock content%}

crm_input_app/templates/crm_input_app/parasDetail.html
{%extends "crm_input_app/base.html"%}

{%block content%}
  <h2>You have successfully saved the following parameter set</h2>
    

	<div class="panel panel-default">
  		<div class="panel-heading">
  			<h3>
  				 {{paras}}

  				  
  				
  			</h3>
  			<small>
  				 	<a href="{% url 'crm_input_app:edit_paras' paras.id%}"> Edit Parameters</a> -
  				 	<a href="{% url 'crm_input_app:result' paras.id %}"> View Result</a>
  			</small>


  		</div>

  		<div class= "panel-body">
  				<ul>
					{%for fieldname, val, display in paras%}

					<li>{{fieldname}} : {{display}}</a></li>


					{%endfor%}

   

 				</ul>

  		</div>

  	</div>



<p>
<a href="{% url 'crm_input_app:parasList'%}">  Back to Parameters List</a>

<p>
<a href="{% url 'crm_input_app:edit_paras' paras.id%}"> Edit Parameters</a>
</p>

<p>

<a href="{% url 'crm_input_app:result' paras.id %}"> View Results</a>
</p>

{%endblock content%}

crm_input_app/templates/crm_input_app/parasList.html
{%extends "crm_input_app/base.html"%}
{%load bootstrap3%}

{% block header%}
<h2> Saved Parameter Sets</h2>
{% endblock%}


{%block content%}
  
<p><a href="{% url 'crm_input_app:new_paras'%}">Add a new parameter set.</a></p>


	{%for paras in paraslist%}
  	
  		<div class="panel panel-default">
  			<div class="panel-heading">
  				<h3>
  				 {{paras}}

  				  
  				
  				</h3>
  				<small>
  				 	<a href="{% url 'crm_input_app:edit_paras' paras.id%}"> Edit Parameters</a> -
  				 	<a href="{% url 'crm_input_app:result' paras.id %}"> View Result</a>
  				 </small>


  			</div>

  			<div class= "panel-body">
  				<ul>
					{%for fieldname, val, display in paras%}

					<li>{{fieldname}} : {{display}}</a></li>


					{%endfor%}

   

 				</ul>

  			</div>
  		</div>





	{%empty%}

	<p>No parameters have been added yet.</p>

	
	{%endfor%}

 

{%endblock content%}

crm_input_app/templates/crm_input_app/result.html
{%extends "crm_input_app/base.html"%}

{%block content%}
  <p> Result Page for Parameter Set {{paras.id}}</p>
<p>

<script type='text/javascript' src='https://riotabqa.appl.kp.org/javascripts/api/viz_v1.js'></script><div class='tableauPlaceholder' style='width: 1004px; height: 1362px;'><object class='tableauViz' width='1004' height='1362' style='display:none;'><param name='host_url' value='https%3A%2F%2Friotabqa.appl.kp.org%2F' /> <param name='site_root' value='&#47;t&#47;TRM-DEV' /><param name='name' value='SHA-1CertificationsMigration&#47;SHAMigrationDashboard' /><param name='tabs' value='yes' /><param name='toolbar' value='yes' /><param name='showVizHome' value='n' /><param name='bootstrapWhenNotified' value='y' /><param name='filter' value='%3AopenAuthoringInTopWindow=true' /><param name='filter' value='%3AbrowserBackButtonUndo=true' /><param name='filter' value='%3AreloadOnCustomViewSave=true' /><param name='filter' value='%3AshowShareOptions=true' /></object></div>


</p>

  <p>
<a href="{% url 'crm_input_app:parasList'%}">  Back to Parameters List</a>

<p>
<a href="{% url 'crm_input_app:edit_paras' paras.id%}"> Edit Parameters</a>
</p>

{%endblock content%}